# I have simply used the YAML file that Dr. Kotthoff used for every one of his code.test.js files for simplicity.
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm i jsverify
    - run: node code.test.js